### ISSUE TITLE
import not possible on 8.0.1

### ISSUE THREAD

**Issue by sverbist0908** [notoriousbdg/vrops-dashboard-custom_vm_summary#1]
tried to import on vROPS 8.0.1 but .zip file extension is not recognized as viable extension to be imported
[vrops-dashboard-custom_vm_summary-master.zip](https://github.com/notoriousbdg/vrops-dashboard-custom_vm_summary/files/4380176/vrops-dashboard-custom_vm_summary-master.zip)

**Comment by notoriousbdg** [comment]
Unzip the file to see the individual content files.
